#!/bin/sh
cd ${0%/*} || exit 1
. $WM_PROJECT_DIR/bin/tools/RunFunctions
show_help() {
    echo "Usage: Allrun [OPTIONS]"
    echo "options:"
    echo "  -m, --onlyMesh  make only meshes"
    echo "  -h, --help      print the usage"
    echo ""
    exit 1
}
optionOld=$OPTIND
OPTIND=1
onlyMesh=0
while getopts "hm-:" opt; do
    case "$opt" in
    -)
        case "${OPTARG}" in
            help) show_help;;
            onlyMesh) onlyMesh=true;;
        esac ;;
    m) onlyMesh=true;;
    h) show_help;;
    esac
done
shift $((OPTIND-1))
OPTIND=$optionOld
runApplication blockMesh
runApplication surfaceFeatures

runApplication decomposePar
runParallel snappyHexMesh -overwrite
runApplication reconstructParMesh -constant -mergeTol 1e-6
rm -rf ./processor*
mv log.decomposePar log.decomposePar-meshing
mv log.reconstructParMesh log.reconstructParMesh-meshing
if [ "$onlyMesh" = true ] ; then
    exit 0
fi

runApplication decomposePar
runParallel $(getApplication)
runApplication reconstructParMesh -constant -mergeTol 1e-6
runApplication reconstructPar
rm -rf ./processor*
